### ISSUE TITLE
config中的vconsole地址配置不生效

### ISSUE THREAD

**Issue by treadpit** [AlloyTeam/AlloyLever#18]
```
/*!
 *  AlloyLever v1.0.2 By dntzhang
 *  Github: https://github.com/AlloyTeam/AlloyLever
 *  MIT Licensed.
 */
```

想使用vconsole的3.x版本，虽然配置了cdn，但加载时还是使用的默认的
 `s.url.cn/qqun/qun/qqweb/m/qun/confession/js/vconsole.min.js` 地址，配置未生效

![image](https://user-images.githubusercontent.com/10692855/31806502-f008a848-b59a-11e7-9709-15a16351f00a.png)

**Comment by zhaoyihong** [comment]
//加载并显示log面板
http://localhost:63342/AlloyLever/index.html?vconsole=show
//加载但不显示log面板
http://localhost:63342/AlloyLever/index.html?vconsole=hide

当你用了这样的方式加载面板时，有个bug：面板直接就show了，你的config还没执行呢．所以建议在config执行后，再判断参数．

**Comment by treadpit** [comment]
@zhaoyihong 好的，谢谢！🍗
