### ISSUE TITLE
console.log的两个问题

### ISSUE THREAD

**Issue by jing2si** [AlloyTeam/AlloyLever#3]
1、console.log('a', 'b', 'c')只能输出一个'a'
2、不能输出对象，console.log(obj)返回的是[object Object]，我试了一下https://github.com/WechatFE/vConsole
这两个问题都不存在，希望改进
:+1:

**Comment by jing2si** [comment]
不能输出对象，console.log(obj)返回的是[object Object]，我试了一下https://github.com/WechatFE/vConsole这两个问题都不存在，希望改进
:+1:

**Comment by dntzhang** [comment]
已解决！~  @jing2si

**Comment by jing2si** [comment]
效率很高~
:100: 

> 不过有点小瑕疵，输出对象能否是格式化后的，一堆在一起不方便查看~

**Comment by dntzhang** [comment]
@jing2si  多谢多谢。已格式化输出:)
